"""omnicounci1l-core — shared types and configuration for OmniCouncil engines."""

from .types import (
    AIResponse,
    AIStatus,
    CircuitState,
    CollectorProgress,
    ComparisonContext,
    ComparisonMetrics,
    DifferenceItem,
    NormalizedResponse,
    ProviderStatus,
    ResultStatus,
    RoundContext,
    RoundContextSummary,
    SemanticUnit,
    SessionState,
    SimilarityMatrix,
    SubmitOptions,
    TaskHandle,
    TaskMode,
    TaskProgress,
    TaskStatus,
    TaskStatusInfo,
    UniqueInsight,
    generate_id,
)
from .config import ComparisonConfig, RateLimitConfig, RetryConfig, SchedulerConfig

__all__ = [
    "AIResponse",
    "AIStatus",
    "CircuitState",
    "CollectorProgress",
    "ComparisonConfig",
    "ComparisonContext",
    "ComparisonMetrics",
    "DifferenceItem",
    "NormalizedResponse",
    "ProviderStatus",
    "RateLimitConfig",
    "ResultStatus",
    "RetryConfig",
    "RoundContext",
    "RoundContextSummary",
    "SchedulerConfig",
    "SemanticUnit",
    "SessionState",
    "SimilarityMatrix",
    "SubmitOptions",
    "TaskHandle",
    "TaskMode",
    "TaskProgress",
    "TaskStatus",
    "TaskStatusInfo",
    "UniqueInsight",
    "generate_id",
]

__version__ = "1.0.0"
